apiVersion: v1
baseDomain: j7ql2.gcp.redhatworkshops.io
metadata:
  name: ocp
platform:
  none: {}
controlPlane:
  name: master
  replicas: 3
  hyperthreading: Enabled
compute:
- name: worker
  replicas: 3
  hyperthreading: Enabled
networking:
  networkType: OVNKubernetes
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23
  serviceNetwork:
  - 172.30.0.0/16
publish: External
pullSecret: |
  {"Pull Secret Here"}
sshKey: |
  ssh-pub-key-here
